DROP TABLE userreservations CASCADE;
DROP TABLE userproductions CASCADE;
DROP TABLE userinventory CASCADE;
DROP TABLE reservations CASCADE;
DROP TABLE inventory CASCADE;
DROP TABLE equipment CASCADE;
DROP TABLE productions CASCADE;
DROP TABLE manufacturers CASCADE;
DROP TABLE users CASCADE;